
-- Insert sample data for articles
INSERT INTO Article (author_id, title, content) VALUES
                                                    (1, 'Article 1', 'Content of article 1'),
                                                    (1, 'Article 2', 'Content of article 2'),
                                                    (2, 'Article 3', 'Content of article 3'),
                                                    (2, 'Article 4', 'Content of article 4'),
                                                    (3, 'Article 5', 'Content of article 5'),
                                                    (3, 'Article 6', 'Content of article 6'),
                                                    (4, 'Article 7', 'Content of article 7'),
                                                    (4, 'Article 8', 'Content of article 8'),
                                                    (5, 'Article 9', 'Content of article 9'),
                                                    (5, 'Article 10', 'Content of article 10'),
                                                    (1, 'Article 11', 'Content of article 11'),
                                                    (2, 'Article 12', 'Content of article 12'),
                                                    (3, 'Article 13', 'Content of article 13'),
                                                    (4, 'Article 14', 'Content of article 14'),
                                                    (5, 'Article 15', 'Content of article 15'),
                                                    (1, 'Article 16', 'Content of article 16'),
                                                    (2, 'Article 17', 'Content of article 17'),
                                                    (3, 'Article 18', 'Content of article 18'),
                                                    (4, 'Article 19', 'Content of article 19'),
                                                    (5, 'Article 20', 'Content of article 20'),
                                                    (1, 'Article 21', 'Content of article 21'),
                                                    (2, 'Article 22', 'Content of article 22'),
                                                    (3, 'Article 23', 'Content of article 23'),
                                                    (4, 'Article 24', 'Content of article 24'),
                                                    (5, 'Article 25', 'Content of article 25'),
                                                    (1, 'Article 26', 'Content of article 26'),
                                                    (2, 'Article 27', 'Content of article 27'),
                                                    (3, 'Article 28', 'Content of article 28'),
                                                    (4, 'Article 29', 'Content of article 29'),
                                                    (5, 'Article 30', 'Content of article 30');

